"""
Mint Street - seed article corpus.
Original editorial summaries of publicly-known startup news.
All prose written for Mint Street; not copied from source publications.
External source links provided for reader attribution.
"""
from datetime import datetime, timezone

SEED_ARTICLES = [
    # ===================== INDIAN STARTUP FUNDING (~10) =====================
    {
        "id": "razorpay-redomicile-india-2025",
        "title": "Razorpay's slow march back to India: what the redomicile reveals about IPO ambition",
        "summary": "The payments unicorn is reversing its US holding-company structure to relist its parent in India, a move increasingly common among late-stage startups eyeing a domestic listing. Razorpay last raised at a roughly $7.5 billion valuation and has signalled IPO intent for the medium term. The redomicile is expected to carry a meaningful one-time tax cost.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/2024/03/razorpay-completes-flip-back-to-india",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-09-12T09:30:00+00:00",
    },
    {
        "id": "zepto-series-g-2024",
        "title": "Zepto pulls in another mega-round as quick commerce burns louder than ever",
        "summary": "The 10-minute delivery startup raised a fresh round at a valuation north of five billion dollars, joining a small club of Indian unicorns repeatedly funded through the late-stage drought. Investors are betting that Zepto's dense dark-store network and improving order economics can outpace the cash burn from a crowded category.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/4393021/pexels-photo-4393021.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/08/29/zepto-funding-quick-commerce-india/",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2024-08-29T11:15:00+00:00",
    },
    {
        "id": "phonepe-india-flip-2022-anniversary",
        "title": "Two years after PhonePe's costly India flip, the playbook is the new normal",
        "summary": "PhonePe's high-profile redomicile from Singapore to India in 2022 triggered a roughly nine-hundred-million-dollar tax outflow for its investors. With Groww, Razorpay and others following the same path, the cost is now seen as a feature of going public on Indian exchanges rather than a one-off anomaly.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/4968382/pexels-photo-4968382.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/phonepe-redomicile-india",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-04-18T08:00:00+00:00",
    },
    {
        "id": "cred-down-round-2024",
        "title": "CRED's revised valuation is a reset, not a rejection, of the premium fintech wedge",
        "summary": "Reports of a secondary round priced below its earlier peak have refocused attention on CRED's path to profitability. The Kunal Shah-led company has steadily widened its product surface from card payments to lending and commerce, even as private markets recalibrate their expectations from late-stage fintechs.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/5926382/pexels-photo-5926382.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/2024/06/cred-down-round",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-06-22T07:45:00+00:00",
    },
    {
        "id": "meesho-profitability-fy24",
        "title": "Meesho's first profitable quarter sets up a credible IPO narrative for 2026",
        "summary": "The horizontal commerce platform reported its maiden quarter of operating profit in 2024, the result of years of unit-economics work and a leaner cost base. Meesho is now widely expected to file for a domestic listing, with bankers reportedly already engaged. Its zero-commission model continues to anchor a Tier-2 and Tier-3 user base.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/5076516/pexels-photo-5076516.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://inc42.com/buzz/meesho-profitability-fy24/",
        "source": "Inc42",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-11-14T10:00:00+00:00",
    },
    {
        "id": "lenskart-secondary-2024",
        "title": "Lenskart's secondary sale pegs the eyewear giant near ten billion dollars",
        "summary": "A secondary share transaction involving Temasek and Fidelity-linked vehicles valued Lenskart in the high single-digit billions, cementing its standing as one of India's most valuable consumer-tech companies. The Peyush Bansal-led firm has been steadily expanding overseas, particularly in Southeast Asia and the Gulf.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/startup/lenskart-valuation-secondary",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-07-08T06:30:00+00:00",
    },
    {
        "id": "boat-ipo-refile-2025",
        "title": "boAt refiles its DRHP as the audio brand bets on a calmer consumer-tech market",
        "summary": "Imagine Marketing, the parent of boAt, has filed afresh with SEBI after shelving an earlier IPO attempt in 2022. The audio-and-wearables company is leaning on improving margins and a leaner SKU base to make its case. The eventual issue size is expected to be materially smaller than the 2022 plan.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/boat-refiles-drhp",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-02-21T09:00:00+00:00",
    },
    {
        "id": "groww-flipback-2024",
        "title": "Groww's reverse flip clears the runway for one of 2025's most-watched IPOs",
        "summary": "Discount broker Groww completed its redomicile to India in mid-2024, a step Singapore-incorporated startups must take before listing on domestic bourses. The Bengaluru company has been profitable for multiple years and is reported to be targeting a listing in the next twelve to eighteen months at a valuation in the high single-digit billions.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/2024/05/groww-completes-india-flip",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-05-30T12:00:00+00:00",
    },
    {
        "id": "tata-digital-restructure-2025",
        "title": "Tata Digital's restructuring shows even conglomerates are not immune to super-app fatigue",
        "summary": "The Tata group's consumer-tech arm has been consolidating businesses and tightening costs under fresh leadership, after years of heavy investment in Tata Neu, BigBasket and 1mg. The exercise is the latest sign that the super-app thesis is being narrowed to a handful of high-conviction wedges across Indian tech.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/tata-digital-restructuring",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-03-10T09:45:00+00:00",
    },
    {
        "id": "postman-valuation-2024",
        "title": "Postman holds the line at $5.6 billion as developer-tools spending normalises",
        "summary": "The API-platform company, founded in Bengaluru and now headquartered in San Francisco, retained its 2021 valuation through subsequent secondary activity even as peers were marked down. Postman serves a large share of Fortune 500 development teams and has been steadily layering on enterprise governance features.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/02/15/postman-developer-tools",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-02-15T07:00:00+00:00",
    },

    # ===================== GLOBAL AI / FUNDING (~6) =====================
    {
        "id": "openai-2026-funding-round",
        "title": "OpenAI's latest round pushes the AI lab past a half-trillion-dollar valuation",
        "summary": "A fresh primary-and-secondary round, led by long-standing backers and joined by sovereign capital, lifted OpenAI's valuation into uncharted territory for a private technology company. The capital is expected to fund compute commitments running into the tens of gigawatts as well as continued frontier-model research.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2026/03/openai-funding-round",
        "source": "TechCrunch",
        "is_pinned": True,
        "priority": 10,
        "published_at": "2026-05-06T13:00:00+00:00",
    },
    {
        "id": "anthropic-series-f-2025",
        "title": "Anthropic's enterprise pivot pays off with a Series funding at a sharply higher mark",
        "summary": "Anthropic, the maker of the Claude family of models, closed a multi-billion-dollar round on the back of accelerating enterprise revenue and expanded compute partnerships with Amazon and Google. The company has positioned itself as a safety-focused alternative for regulated industries and large model deployments.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/8438923/pexels-photo-8438923.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/articles/2025/anthropic-funding",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 9,
        "published_at": "2025-10-02T14:20:00+00:00",
    },
    {
        "id": "mistral-european-bet-2024",
        "title": "Mistral's open-weight push makes it Europe's most credible challenger to US AI labs",
        "summary": "The Paris-based startup secured a sizeable round to fund larger training runs and an expanded enterprise offering. Mistral has leaned into a release strategy that mixes open-weight models with hosted commercial APIs, positioning itself as a sovereign option for European governments and regulated enterprises.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/06/mistral-funding-round",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-06-11T08:30:00+00:00",
    },
    {
        "id": "perplexity-search-2025",
        "title": "Perplexity stretches into a teen-billion valuation as AI search starts taking real queries",
        "summary": "The conversational-search startup raised at a sharply higher mark on the back of growing user numbers and a recently launched browser. Perplexity is now competing not only with Google's AI Overviews but also with model labs trying to vertically integrate into consumer search.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/articles/2025/perplexity-valuation",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-12-15T10:10:00+00:00",
    },
    {
        "id": "figma-adobe-collapse-2024",
        "title": "Eighteen months after the Adobe deal collapsed, Figma is quietly rebuilding for an IPO",
        "summary": "After regulators in the UK and EU effectively killed Adobe's twenty-billion-dollar acquisition, Figma collected a sizeable break fee and accelerated its product roadmap with AI-assisted design. The company has been steadily moving towards a public-markets exit, with bankers tipped to be engaged.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/01/figma-after-adobe",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-01-22T09:00:00+00:00",
    },
    {
        "id": "databricks-pre-ipo-2025",
        "title": "Databricks' pre-IPO round signals confidence that the AI-data flywheel is finally working",
        "summary": "The data-and-AI platform closed a large primary round at a valuation in the low tens of billions ahead of an eventual listing. Databricks has been steadily widening its product surface from analytics into model training and serving, and reports rising AI-product revenue mix.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/1181243/pexels-photo-1181243.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/articles/2025/databricks-pre-ipo",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-06-19T11:00:00+00:00",
    },

    # ===================== INDIAN IPOs / DRHPs (~5) =====================
    {
        "id": "swiggy-ipo-2024",
        "title": "Swiggy's IPO is a referendum on India's appetite for late-stage tech listings",
        "summary": "The food-and-delivery giant filed its DRHP earlier in the year and is targeting a domestic listing at a meaningfully lower valuation than its 2022 peak. The eventual price discovery will help calibrate expectations for the long pipeline of consumer-internet companies eyeing 2025 listings.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/4393668/pexels-photo-4393668.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/swiggy-ipo-filing",
        "source": "Mint",
        "is_pinned": True,
        "priority": 9,
        "published_at": "2024-09-26T10:30:00+00:00",
    },
    {
        "id": "ola-electric-listing-2024",
        "title": "Ola Electric becomes the first pure-play Indian EV company to ring the bell",
        "summary": "Bhavish Aggarwal's electric two-wheeler venture completed a high-profile listing on Indian bourses in 2024, opening up the public-markets thesis for domestic electric mobility. The stock has since seen sharp swings as investors weigh service-network issues against a still-leading scooter market share.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/ola-electric-listing",
        "source": "Mint",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2024-08-09T05:45:00+00:00",
    },
    {
        "id": "firstcry-listing-2024",
        "title": "FirstCry's listing tests how public markets price niche commerce franchises",
        "summary": "Brainbees Solutions, the parent of FirstCry, completed its IPO in 2024 at a valuation modestly below its last private round. The mother-and-baby retailer combines an omnichannel footprint with private-label brands and overseas expansion through its Globalbees and FirstCry Arabia plays.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/ipo/firstcry-listing",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-08-13T07:30:00+00:00",
    },
    {
        "id": "mamaearth-anniversary-2024",
        "title": "A year after listing, Mamaearth's parent is a case study in post-IPO discipline",
        "summary": "Honasa Consumer, the parent of Mamaearth, completed a full financial year as a listed company in 2024. The maiden D2C beauty IPO of its scale has continued to lean on its smaller brands and channel-mix discipline rather than aggressive ad spending to defend margins.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/3735632/pexels-photo-3735632.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/honasa-consumer-mamaearth",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-11-07T08:15:00+00:00",
    },
    {
        "id": "nse-listing-talks-2026",
        "title": "NSE's long-pending listing inches forward as SEBI signals procedural clarity",
        "summary": "The National Stock Exchange, India's largest bourse by turnover, has been awaiting regulatory clearances to list itself for years. Recent commentary from SEBI leadership suggests the remaining gating items are nearing resolution, setting up what would be one of the most significant financial-sector IPOs in the country.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/nse-listing-progress",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2026-02-04T09:00:00+00:00",
    },

    # ===================== M&A / EXITS (~5) =====================
    {
        "id": "walmart-flipkart-anniversary-2024",
        "title": "Six years on, Walmart's Flipkart bet is finally looking less like a write-down",
        "summary": "Walmart's 2018 acquisition of Flipkart was widely seen as expensive at the time. Improving profitability at the marketplace, alongside PhonePe's standalone trajectory, has begun to validate the strategic logic of the deal, even as the eventual exit path for Walmart's stake remains open.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/4391470/pexels-photo-4391470.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/05/walmart-flipkart-six-years",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-05-09T11:00:00+00:00",
    },
    {
        "id": "byjus-collapse-2024",
        "title": "Byju's unwinding is the clearest case study in zero-rate-era excess yet",
        "summary": "Once India's most valuable startup, Byju's has entered insolvency proceedings amid creditor disputes, layoffs and missed bond payments. The collapse has prompted broader scrutiny of corporate-governance practices in late-stage Indian startups and the appetite of global lenders for venture-style risk.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/5905709/pexels-photo-5905709.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/byjus-insolvency",
        "source": "Mint",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2024-07-17T06:00:00+00:00",
    },
    {
        "id": "bharatpe-phonepe-truce-2024",
        "title": "BharatPe and PhonePe finally end their trademark feud with a settlement",
        "summary": "After several years of litigation across courts and tribunals, the two fintechs agreed to drop claims and counterclaims related to the use of the suffix 'Pe'. The settlement clears a long-running overhang for both companies as they continue to expand into lending and offline payments.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/5980585/pexels-photo-5980585.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/bharatpe-phonepe-settlement",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-04-26T07:45:00+00:00",
    },
    {
        "id": "paytm-pivot-2024",
        "title": "Paytm's post-PPBL pivot is leaner, but the road back to growth is steep",
        "summary": "After the RBI restrictions on Paytm Payments Bank, One97 Communications has reshaped its business around third-party banking partnerships, merchant payments and loan distribution. Quarterly losses have narrowed, but core monthly user metrics took longer to recover than the company had initially guided.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/4968383/pexels-photo-4968383.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/paytm-pivot",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-10-31T09:20:00+00:00",
    },
    {
        "id": "tata-bigbasket-quick-commerce-2025",
        "title": "Tata folds BBNow deeper into BigBasket as quick commerce squeezes margins",
        "summary": "The Tata-owned grocer has restructured its 10-to-30-minute service after a year of intense competition from Zepto, Blinkit and Swiggy Instamart. The combined entity is leaning on shared dark stores and a more cautious city-rollout pace, rather than the all-out expansion that defined 2023.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/bigbasket-bbnow-restructure",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-04-08T08:10:00+00:00",
    },

    # ===================== DEEPTECH / CLIMATE / EV / SPACE (~5) =====================
    {
        "id": "agnikul-orbital-launch-2024",
        "title": "Agnikul's sub-orbital test puts an Indian private launcher within sight of orbit",
        "summary": "The IIT-Madras incubated startup successfully tested its single-stage Agnibaan SOrTeD launch vehicle from its own private launch pad in Sriharikota. The flight, built around a 3D-printed engine, marks a meaningful step towards small-satellite launch services from an entirely private Indian stack.",
        "category": "deeptech",
        "category_label": "Deeptech",
        "image": "https://images.pexels.com/photos/586063/pexels-photo-586063.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/agnikul-sorted-launch",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-05-30T05:30:00+00:00",
    },
    {
        "id": "skyroot-vikram-2025",
        "title": "Skyroot lines up its first orbital attempt as private launches become routine",
        "summary": "Hyderabad-based Skyroot Aerospace, which flew India's first private sub-orbital rocket in 2022, is preparing for its first orbital flight of the Vikram I vehicle. The company has steadily moved through engine and stage tests and is positioning itself as a low-cost option for small-satellite operators.",
        "category": "deeptech",
        "category_label": "Deeptech",
        "image": "https://images.pexels.com/photos/586056/pexels-photo-586056.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/skyroot-vikram-i",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-08-21T07:00:00+00:00",
    },
    {
        "id": "ather-ipo-2025",
        "title": "Ather Energy's IPO is a test of investor appetite for the second-place EV story",
        "summary": "The Hero MotoCorp-backed electric two-wheeler maker listed on Indian bourses in 2025 at a valuation modestly below its last private round. With Ola Electric already public, Ather's price discovery is being read as a signal of how durable investors believe the Indian EV opportunity is.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/9242841/pexels-photo-9242841.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/ather-energy-listing",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-05-06T09:30:00+00:00",
    },
    {
        "id": "ola-electric-service-network-2025",
        "title": "Ola Electric's service-network strain is becoming a stock-price story",
        "summary": "Customer complaints about service turnaround and software issues have weighed on Ola Electric's listed shares through 2024 and 2025. The company has announced fresh investments in its service footprint and a tighter quality-control regime, but the operational drag has narrowed its market-share lead.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/companies/ola-electric-service",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-01-30T08:00:00+00:00",
    },
    {
        "id": "indian-space-policy-2024",
        "title": "India's new spacetech FDI regime opens the door for a wave of private capital",
        "summary": "Amended FDI rules in the space sector, alongside IN-SPACe authorisation pathways, have meaningfully reduced the regulatory friction for foreign capital into Indian launch and satellite startups. Industry bodies expect the changes to translate into a noticeably larger funding pipeline for the segment.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/586031/pexels-photo-586031.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/economy/india-space-fdi-policy",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-03-04T07:30:00+00:00",
    },

    # ===================== POLICY (~4) =====================
    {
        "id": "gst-online-gaming-2024",
        "title": "A year of 28% GST on gaming has reshaped the real-money industry's economics",
        "summary": "The Council's 2023 decision to levy GST on the full face value of bets has, by 2024, prompted layoffs, consolidation and product redesigns across India's real-money gaming companies. Industry bodies continue to lobby for relief, but most operators have publicly rebuilt their plans around the new tax base.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/6963944/pexels-photo-6963944.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/economy/gst-online-gaming-one-year",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-10-01T08:00:00+00:00",
    },
    {
        "id": "dpdp-rules-2025",
        "title": "Draft DPDP rules give Indian startups a first real look at compliance costs",
        "summary": "The Ministry of Electronics and IT released draft rules under the Digital Personal Data Protection Act, opening up consultations on consent managers, child data and breach notifications. Founders and counsel are now beginning the difficult work of mapping product flows against an enforceable Indian privacy regime.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/news/india/dpdp-draft-rules",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-01-08T06:30:00+00:00",
    },
    {
        "id": "rbi-default-loss-guarantee-2024",
        "title": "RBI's tighter digital-lending rules trim the easy-money edge from co-lending",
        "summary": "The central bank's framework around default-loss guarantees and digital-lending intermediaries has been operational for over a year, forcing fintechs to disclose risk-sharing structures and recalibrate partnerships with banks and NBFCs. The result has been smaller but more durable digital-lending books.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/210742/pexels-photo-210742.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/industry/banking/rbi-digital-lending",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-12-12T09:15:00+00:00",
    },
    {
        "id": "sebi-startup-listings-2025",
        "title": "SEBI's tweaks to the IGP make a domestic listing slightly less painful for startups",
        "summary": "The market regulator has eased disclosure timelines, promoter-lockup expectations and ESOP cooling-off rules for companies using the Innovators Growth Platform and the main board. Bankers say the changes do not, by themselves, unlock listings but remove several technical irritants for founder-led companies.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/sebi-startup-listing-rules",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-07-22T10:00:00+00:00",
    },

    # ===================== D2C / SaaS (~3) =====================
    {
        "id": "wakefit-drhp-2025",
        "title": "Wakefit's DRHP positions the sleep brand as a profitable D2C anomaly",
        "summary": "The Bengaluru-headquartered mattress and home-solutions brand filed for an IPO in 2025 after reporting full-year operating profit. Wakefit's offering is being read as a test case for D2C listings that lean on disciplined unit economics rather than aggressive growth pricing.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/ipo/wakefit-drhp",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-11-03T08:00:00+00:00",
    },
    {
        "id": "freshworks-margin-shift-2024",
        "title": "Freshworks' AI bet shows up in margins before it shows up in headline growth",
        "summary": "The Chennai-and-California SaaS company has steadily layered AI-assistant features into its IT-service and CRM products, with management pointing to gradually improving operating margins. Revenue growth has decelerated from its 2021 peak but the operating leverage is now visible.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2024/11/freshworks-ai-margins",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-11-20T07:30:00+00:00",
    },
    {
        "id": "zoho-ai-stack-2025",
        "title": "Zoho's home-grown AI stack is the quiet bet that could redefine its enterprise pitch",
        "summary": "Sridhar Vembu's Zoho has continued to invest in its own models and inference infrastructure rather than wholly relying on third-party APIs. The bootstrapped Indian SaaS giant frames the choice as a long-term play on data sovereignty and unit economics, even as it lengthens product timelines.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/zoho-ai-stack",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-09-18T09:45:00+00:00",
    },

    # ===================== INDIAN VCs (~2) =====================
    {
        "id": "peak-xv-split-2024",
        "title": "Peak XV's first full year on its own resets expectations for Indian venture",
        "summary": "After parting ways with Sequoia Capital in 2023, Peak XV Partners has steadily articulated its own investment cadence across early- and growth-stage funds. The firm has continued to back select India and Southeast Asia themes while paring back some of the late-stage exposure that defined the prior era.",
        "category": "vc",
        "category_label": "VC",
        "image": "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/peak-xv-one-year",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-06-04T08:30:00+00:00",
    },
    {
        "id": "blume-fund-v-2026",
        "title": "Blume's fifth fund leans further into deeptech as early-stage cheques get bigger",
        "summary": "Blume Ventures has begun deploying its largest fund to date with a more deliberate tilt towards spacetech, climate hardware and developer tools. Partners have signalled a slightly higher average cheque size and a longer time horizon, reflecting how early-stage Indian venture has matured over the last decade.",
        "category": "vc",
        "category_label": "VC",
        "image": "https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/news/blume-fund-v",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2026-01-14T07:00:00+00:00",
    },
]


# ===================== ADDITIONAL BATCHES (60 articles, 4 topical files) =====================
from seed.articles_funding import ARTICLES as _funding_batch
from seed.articles_trending import ARTICLES as _trending_batch
from seed.articles_newindia import ARTICLES as _newindia_batch
from seed.articles_global import ARTICLES as _global_batch

SEED_ARTICLES = (
    SEED_ARTICLES
    + _funding_batch
    + _trending_batch
    + _newindia_batch
    + _global_batch
)


def get_seed_articles():
    return SEED_ARTICLES


if __name__ == "__main__":
    print(f"Loaded {len(SEED_ARTICLES)} seed articles")
    for a in SEED_ARTICLES[:3]:
        print(f"- [{a['category_label']}] {a['title']}")
