"""Mint Street - new India + policy seed batch C (15 articles)."""

ARTICLES = [
    # ------------------------ Emerging startups (D2C / consumer) ------------------------
    {
        "id": "atomberg-ceiling-fan-bet-2025",
        "title": "Atomberg's quiet bet: how a fan startup is teaching India to pay a premium for efficiency",
        "summary": "Atomberg has spent the better part of a decade selling BLDC ceiling fans on the unfashionable promise of lower power bills. The Mumbai-headquartered company has steadily climbed into the top tier of organised fan brands, with new factory capacity and a widening kitchen-appliance line-up. Its pitch resonates with a category where margins are thin and brand pull historically weak.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/4108266/pexels-photo-4108266.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/atomberg-revenue-growth",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-03-18T09:00:00+00:00",
    },
    {
        "id": "blusmart-fleet-model-2025",
        "title": "BluSmart's all-EV gamble runs into the hard math of fleet ride-hailing",
        "summary": "The Gurugram-based ride-hailing operator has built a closed-loop EV fleet across Delhi-NCR, Bengaluru and Mumbai, an unusual architecture in a market dominated by aggregator models. Investors continue to back the unit-economics story, but questions persist around utilisation, charging-infrastructure costs and the company's overlap with sister entity Gensol.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/110844/pexels-photo-110844.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://inc42.com/buzz/blusmart-ev-fleet-economics",
        "source": "Inc42",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-01-22T07:30:00+00:00",
    },
    {
        "id": "country-delight-subscription-2024",
        "title": "Country Delight's subscription milk model is finally finding its profitability arc",
        "summary": "The Gurugram dairy startup has been narrowing losses as route density improves and its private-label range moves beyond milk into ghee, paneer and curd. Country Delight's recurring-revenue model gives it cohort visibility that few D2C grocery players enjoy, even as quick commerce eats into impulse purchases across categories.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/236010/pexels-photo-236010.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/start-ups/country-delight-financials",
        "source": "Mint",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-09-04T08:15:00+00:00",
    },
    {
        "id": "captain-fresh-seafood-roll-up-2024",
        "title": "Captain Fresh stitches a global seafood platform out of fragmented Indian supply",
        "summary": "Bengaluru-based Captain Fresh has spent the last two years acquiring processors and distributors across the United States and Europe, turning what began as a B2B marketplace for Indian seafood into a vertically integrated exporter. The company has signalled an eventual public listing, with markets watching whether the roll-up thesis translates into operating leverage.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/2098115/pexels-photo-2098115.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/captain-fresh-acquisitions",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-10-29T10:45:00+00:00",
    },
    # ------------------------ Founder profiles ------------------------
    {
        "id": "sridhar-vembu-zoho-tenkasi-profile-2024",
        "title": "Sridhar Vembu and the Tenkasi experiment: building global SaaS from a Tamil Nadu village",
        "summary": "Zoho's founder has spent years moving engineering teams from Chennai and Bengaluru into smaller towns across Tamil Nadu, with Tenkasi as the most visible outpost. The model - bootstrapped, employee-funded, allergic to venture capital - has produced a SaaS company with annual revenues that few Indian internet firms can match. Vembu's recent move into rural manufacturing extends the same thesis into hardware.",
        "category": "saas",
        "category_label": "SaaS",
        "image": "https://images.pexels.com/photos/3184302/pexels-photo-3184302.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/companies/people/sridhar-vembu-zoho-tenkasi",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-12-11T09:30:00+00:00",
    },
    {
        "id": "nithin-kamath-zerodha-after-stroke-2024",
        "title": "Nithin Kamath's quieter year: succession, sabbaticals and the case against perpetual founder mode",
        "summary": "The Zerodha co-founder has spent 2024 publicly recalibrating after a health scare, sharing leadership across the company and pushing brother Nikhil and a wider executive bench into more visible roles. The Bengaluru broker remains the rare profitable consumer-fintech operator in India, and Kamath's evolving posture on founder longevity is shaping a broader conversation in the ecosystem.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/nithin-kamath-zerodha-leadership",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-08-19T07:00:00+00:00",
    },
    {
        "id": "ghazal-alagh-mamaearth-post-ipo-2025",
        "title": "Ghazal Alagh after the IPO: rebuilding Mamaearth's brand math under public-market scrutiny",
        "summary": "Honasa Consumer's co-founder has spent the months since the company's listing pushing the portfolio beyond Mamaearth into newer labels such as The Derma Co. and Aqualogica. Public-market investors have been less forgiving of growth wobbles than private backers were, forcing a sharper focus on offline distribution and category-level profitability.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/companies/honasa-mamaearth-results",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-05-06T10:30:00+00:00",
    },
    {
        "id": "aadit-palicha-zepto-profile-2024",
        "title": "Aadit Palicha's compressed decade: how Zepto's young founder is navigating the quick-commerce war",
        "summary": "Still in his early twenties, Zepto's co-founder has raised multiple mega-rounds, fought off intense competition from Zomato-owned Blinkit and Swiggy Instamart, and pushed the Mumbai-headquartered company toward an eventual public listing. The founder's bet on dense dark-store coverage has held up in metros, even as profitability for the category remains contested.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/4393668/pexels-photo-4393668.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://inc42.com/features/aadit-palicha-zepto-profile",
        "source": "Inc42",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-11-26T09:45:00+00:00",
    },

    # ------------------------ Policy ------------------------
    {
        "id": "pli-2-electronics-review-2025",
        "title": "PLI 2.0 for electronics: what the second-round rules say about India's manufacturing ambition",
        "summary": "A refreshed Production-Linked Incentive scheme aimed at IT hardware and components has drawn in a broader set of contract manufacturers and component vendors than the first wave. The Centre's emphasis has shifted from final-assembly to deeper value addition, with eligibility criteria nudging applicants toward local sourcing of displays, batteries and mechanicals.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/3862632/pexels-photo-3862632.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/economy/pli-electronics-second-round",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-02-14T08:30:00+00:00",
    },
    {
        "id": "angel-tax-repeal-followthrough-2024",
        "title": "After the angel-tax repeal: what's still unresolved for early-stage fundraising in India",
        "summary": "The 2024 Union Budget scrapped Section 56(2)(viib) for all classes of investors, ending nearly a decade of friction around valuations of unlisted shares. Founders and CFOs say the relief has simplified term-sheet conversations, but legacy assessments, transfer-pricing scrutiny and ESOP-related questions remain live issues across DPIIT-recognised startups.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/5849577/pexels-photo-5849577.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/angel-tax-abolished-budget-2024",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2024-07-25T06:45:00+00:00",
    },
    {
        "id": "ondc-scale-up-2025",
        "title": "ONDC at the awkward middle: order volumes climb but the unit economics are still a puzzle",
        "summary": "The Open Network for Digital Commerce has crossed meaningful monthly order volumes, driven largely by mobility and grocery use-cases, but seller subsidies and disputes over buyer-app incentives have kept the network's economics under debate. Policymakers continue to position ONDC as a long-horizon public infrastructure bet rather than a short-cycle commercial platform.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/5076531/pexels-photo-5076531.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.moneycontrol.com/news/business/ondc-monthly-orders",
        "source": "Moneycontrol",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-04-21T10:00:00+00:00",
    },
    {
        "id": "account-aggregator-consent-flows-2025",
        "title": "Account Aggregator hits scale, but consent-flow drop-offs are now the bottleneck",
        "summary": "The AA framework has crossed material thresholds in linked accounts and successful data fetches, with lenders, wealth-tech apps and personal-finance platforms among the heaviest users. Industry data suggests that user friction at the consent step - especially among first-time AA users - is the next design challenge for the RBI-supervised network.",
        "category": "fintech",
        "category_label": "Fintech",
        "image": "https://images.pexels.com/photos/4968630/pexels-photo-4968630.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://inc42.com/features/account-aggregator-scale-2025",
        "source": "Inc42",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-03-05T07:15:00+00:00",
    },
    {
        "id": "ifsca-giftcity-fund-rules-2025",
        "title": "IFSCA's GIFT City fund rules are quietly redrawing where Indian VCs domicile their pools",
        "summary": "Successive rounds of regulation from the International Financial Services Centres Authority have made GIFT City a more credible jurisdiction for fund managers raising overseas capital. Several India-focused venture and PE firms have set up or migrated feeder vehicles, citing tax clarity and a single-window regulator as the marginal pull factors over Singapore and Mauritius.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/2068975/pexels-photo-2068975.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/market/gift-city-aif-rules",
        "source": "Mint",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-01-30T09:20:00+00:00",
    },

    # ------------------------ Regional hubs ------------------------
    {
        "id": "hyderabad-deeptech-thub-2025",
        "title": "Hyderabad's quiet ascent: how T-Hub and a deeptech cohort are reshaping the city's startup story",
        "summary": "Once known mainly for its IT services campuses, Hyderabad has emerged as a credible base for deeptech, life-sciences and SaaS companies, with state-backed institutions such as T-Hub and WE Hub anchoring the ecosystem. Founders cite cheaper talent, supportive state government and proximity to pharma and aerospace clusters as the differentiators against Bengaluru.",
        "category": "startups",
        "category_label": "Startups",
        "image": "https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/hyderabad-startup-ecosystem-2025",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-05-12T08:00:00+00:00",
    },
    {
        "id": "indore-tier2-d2c-cluster-2024",
        "title": "Indore's D2C cluster: a tier-2 city quietly punching above its weight in consumer brands",
        "summary": "A small but growing set of consumer startups headquartered in Indore - spanning food, snacks and personal care - is making the case that brand-building in India no longer requires a Bengaluru or Mumbai postcode. Lower fulfilment costs, proximity to manufacturing belts in Madhya Pradesh and a returning diaspora of founders are reshaping the city's commercial identity.",
        "category": "d2c",
        "category_label": "D2C",
        "image": "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://inc42.com/features/indore-d2c-startups",
        "source": "Inc42",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-12-03T07:45:00+00:00",
    },
]
