"""Mint Street — Indian startup funding seed batch A (15 articles)."""

ARTICLES = [
    # ---------- 1. Consumer fintech / neobank ----------
    {
        "id": "jupiter-series-c-extension-2024",
        "title": "Jupiter's quiet extension round signals the new patience inside India's neobank story",
        "summary": "Jitendra Gupta's consumer banking platform pulled a follow-on tranche to its Series C as investors trimmed expectations across the neobank cohort. The round appears flat to mildly down on paper, but extends runway through the long NBFC build-out that Jupiter has been quietly assembling. Bankers say the focus has shifted from MAU growth to credit unit economics.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/4968382/pexels-photo-4968382.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-05-08T09:15:00+00:00",
    },
    # ---------- 2. Social commerce / vernacular ----------
    {
        "id": "sharechat-debt-restructure-2024",
        "title": "ShareChat's debt-led raise is the clearest sign yet that vernacular social is repricing",
        "summary": "Mohalla Tech, parent of ShareChat and Moj, closed a convertible debt facility this year amid a sharp markdown by existing backers. The capital structure shift, with venture debt alongside earlier equity from Google and Tiger Global, gives the company room to defer a priced round. Industry sources say the valuation has reset by more than half from its 2022 peak.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/267350/pexels-photo-267350.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-02-19T11:00:00+00:00",
    },
    # ---------- 3. Home services / horizontal marketplace ----------
    {
        "id": "urban-company-pre-ipo-secondary-2025",
        "title": "Urban Company's pre-IPO secondary is a litmus test for India's services-tech multiples",
        "summary": "A late-stage secondary in Urban Company saw existing investors trim positions to incoming domestic mutual funds, in a structure increasingly typical of pre-IPO Indian unicorns. The implied valuation, according to filings reviewed by industry trackers, sits modestly above the company's 2021 priced round. The deal sets a reference price for the planned domestic listing.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/4239031/pexels-photo-4239031.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-03-04T08:30:00+00:00",
    },
    # ---------- 4. Health / e-pharmacy down-round ----------
    {
        "id": "pharmeasy-rights-issue-2024",
        "title": "PharmEasy's rights issue cements one of the steepest markdowns in Indian unicorn history",
        "summary": "API Holdings priced a fresh rights issue at a fraction of its peak Series F valuation, formalising a markdown that several investors had already flagged on their books. The round was largely subscribed by existing backers and is being used to retire debt taken on for the Thyrocare acquisition. The reset is now a reference point for late-stage Indian healthtech.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2024-01-26T07:50:00+00:00",
    },
    # ---------- 5. Used cars / inventory-heavy ----------
    {
        "id": "cars24-debt-stack-2025",
        "title": "Cars24 leans deeper into debt as the used-car flywheel demands more working capital",
        "summary": "The Vikram Chopra-led marketplace expanded its debt facilities through a mix of NBFC lines and structured paper, a route preferred by inventory-heavy consumer platforms. The move comes ahead of an expected equity raise that bankers say could be priced flat to its last unicorn round. Cars24's overseas operations are reportedly closer to break-even than the India book.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-01-21T10:20:00+00:00",
    },
    # ---------- 6. Used cars #2 (Spinny) ----------
    {
        "id": "spinny-follow-on-tiger-2024",
        "title": "Spinny's quiet follow-on round narrows the field in India's used-car duopoly",
        "summary": "Spinny secured a follow-on tranche from existing backers including Tiger Global affiliates, with the round structured to avoid a priced markdown. The company has shrunk its city footprint over eighteen months and is leaning on its hub model in the NCR. The cap table now looks more conservative than its 2021 unicorn raise.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/3608542/pexels-photo-3608542.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2024-09-10T09:45:00+00:00",
    },
    # ---------- 7. B2B commerce / SME ----------
    {
        "id": "ofbusiness-pre-ipo-2025",
        "title": "OfBusiness raises a pre-IPO round and quietly becomes one of India's most profitable unicorns",
        "summary": "The B2B raw-materials and SME-lending platform closed a fresh round ahead of its expected domestic listing, with the implied valuation comfortably above its previous priced level. Unlike most of its peer set, OfBusiness has compounded profits for several consecutive years through a tightly capital-efficient model. The IPO is now widely expected within the next four quarters.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/4481327/pexels-photo-4481327.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2025-06-17T08:00:00+00:00",
    },
    # ---------- 8. D2C rollup ----------
    {
        "id": "mensa-brands-down-round-2024",
        "title": "Mensa Brands' fresh raise crystallises the long unwind of the Thrasio-style rollup thesis",
        "summary": "The Ananth Narayanan-led house of brands closed a round below its 2022 unicorn level, in line with the broader recalibration of the D2C rollup category. Mensa has been pruning brands and shifting toward portfolio profitability over breadth. The funding extends runway as it explores selective bolt-ons rather than the aggressive M&A of its early years.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/3962294/pexels-photo-3962294.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-07-30T07:30:00+00:00",
    },
    # ---------- 9. Direct-to-fridge perishables ----------
    {
        "id": "licious-secondary-2024",
        "title": "Licious's secondary transaction trims valuation but anchors a sharper unit-economics story",
        "summary": "A secondary share sale in the meat-and-seafood platform implied a haircut to its earlier Series G mark, while bringing in fresh strategic capital. Licious has spent two years narrowing city presence and consolidating cold-chain operations under a leaner footprint. The reset valuation, sources say, is now comparable with public-market peers in premium FMCG.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-10-15T10:00:00+00:00",
    },
    # ---------- 10. Dairy / subscription ----------
    {
        "id": "country-delight-series-e-2025",
        "title": "Country Delight's Series E goes through with quiet domestic-led participation",
        "summary": "The subscription-first dairy platform closed a Series E with participation from existing growth investors and at least one large domestic family office. The deal continues a trend of Indian late-stage rounds tilting toward domestic LP capital rather than global crossover funds. Country Delight has steadily layered adjacent categories around its core milk subscription.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-09-23T09:00:00+00:00",
    },
    # ---------- 11. Seafood / cold chain ----------
    {
        "id": "captain-fresh-series-d-2024",
        "title": "Captain Fresh's Series D narrows the B2B seafood thesis into a leaner export book",
        "summary": "The seafood supply-chain platform closed a Series D that emphasised its international wholesale operations, with backers including Tiger Global affiliates and Nekkanti family interests. The round arrives as Captain Fresh restructures its India retail experiments and leans into the higher-margin export corridor. Bankers say a pre-IPO round is the most likely next step.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/1267697/pexels-photo-1267697.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-04-05T08:45:00+00:00",
    },
    # ---------- 12. Credit-card-fintech-pivot ----------
    {
        "id": "slice-merger-bridge-2024",
        "title": "Slice's post-merger bridge round is less about cash and more about a regulated balance sheet",
        "summary": "Following its merger with North East Small Finance Bank, Slice raised a bridge round whose value is symbolic rather than financial — anchoring its standing as a bank-led fintech under RBI oversight. The capital is going into compliance, treasury and a slimmed-down lending set. The NBFC-era valuation no longer maps cleanly onto the merged entity.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/5926382/pexels-photo-5926382.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-12-11T07:45:00+00:00",
    },
    # ---------- 13. SME credit ----------
    {
        "id": "aye-finance-pre-ipo-2025",
        "title": "Aye Finance's pre-IPO round underlines the boring math of India's micro-enterprise lender boom",
        "summary": "The MSME-focused NBFC closed a pre-IPO round with sovereign-linked vehicles and existing growth backers, ahead of a planned domestic listing. Aye Finance has compounded its loan book at a measured pace while keeping credit costs disciplined through a tightly underwritten customer base. Valuation has, unusually, trended up across each successive round.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-02-12T10:30:00+00:00",
    },
    # ---------- 14. Revenue-based / debt marketplace ----------
    {
        "id": "recur-club-series-a-2025",
        "title": "Recur Club's Series A reframes the debt marketplace as an alternative to dilutive equity",
        "summary": "The Eklavya Gupta-led debt marketplace closed a Series A from fintech-focused funds, capping a year in which the platform reportedly more than doubled its monthly disbursal run-rate. Recur Club's pitch has resonated with Series B-and-beyond startups looking to extend runway without resetting valuations. The category now competes directly with venture debt firms.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/210607/pexels-photo-210607.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 5,
        "published_at": "2025-04-08T09:15:00+00:00",
    },
    # ---------- 15. Beauty / D2C ----------
    {
        "id": "sugar-cosmetics-series-e-2024",
        "title": "SUGAR Cosmetics' Series E lands at a measured mark as colour beauty consolidates",
        "summary": "Vineeta Singh's colour cosmetics company closed a Series E with new participation from L Catterton and existing backers, priced modestly above its previous level. SUGAR has been expanding offline distribution sharply while its digital channel matures into a steady, profitable mix. The funding sets up a domestic IPO window bankers expect in 2026.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://mintstreet.in",
        "source": "Mint Street",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-03-22T08:10:00+00:00",
    },
]
