"""Mint Street — global + cross-border seed batch D (15 articles)."""

ARTICLES = [
    {
        "id": "stripe-secondary-tender-2025",
        "title": "Stripe's tender offer lifts the payments giant past its 2021 peak — and India watches the rails",
        "summary": "A fresh employee tender at Stripe valued the company in the high single-digit-trillion-rupee territory, recovering most of the markdown it took during the rate-hike cycle. For Indian fintechs eyeing global expansion, the print is a useful comparable on how public-market patience returns first to category leaders. Stripe's India ambitions, dormant for years, remain a watch-list item for domestic merchants and acquirers.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/6347707/pexels-photo-6347707.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/stripe-tender-offer-valuation",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2025-03-12T08:30:00+00:00",
    },
    {
        "id": "klarna-listing-aftermath-2025",
        "title": "Klarna's New York debut gives Indian BNPL a fresh, complicated mirror to study",
        "summary": "The Swedish buy-now-pay-later firm's US listing closed its first sessions above the IPO range, validating a slimmed-down cost base and an AI-driven support stack that cut headcount sharply. The Indian BNPL cohort, which has spent the last two years digesting RBI's digital-lending guardrails, will read Klarna's numbers carefully — particularly the cost-to-serve metric that has long been the category's Achilles heel.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/4968630/pexels-photo-4968630.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.reuters.com/markets/deals/klarna-ipo-debut",
        "source": "Reuters",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-09-18T13:45:00+00:00",
    },
    {
        "id": "shein-ipo-pivot-2025",
        "title": "Shein's listing venue churn ends in London, and India's fast-fashion brands take notes",
        "summary": "After regulatory friction in both New York and Hong Kong, the fast-fashion exporter steered toward a London float, agreeing to disclosures around supply-chain provenance that are unusually stringent for the sector. For Indian D2C apparel brands that have long bristled at Shein-style price points, the deal sets a new bar for ESG storytelling — and possibly for the kind of audits domestic exchanges may eventually demand.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/5868722/pexels-photo-5868722.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.ft.com/content/shein-london-listing",
        "source": "Financial Times",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-04-02T10:00:00+00:00",
    },
    {
        "id": "bytedance-india-stranded-2024",
        "title": "ByteDance's stranded India business resurfaces in valuation talk as global buyback widens",
        "summary": "A new ByteDance employee buyback re-rated the parent in the hundreds of billions of dollars, but the conspicuous absence of any India revenue line continues to draw attention. TikTok's 2020 ban left behind a sizable engineering footprint in Gurugram and Bengaluru that the company has been quietly winding down. Indian creators, meanwhile, have moved on to Instagram Reels and YouTube Shorts, and the policy door remains firmly shut.",
        "category": "tech",
        "category_label": "Tech",
        "image": "https://images.pexels.com/photos/5081930/pexels-photo-5081930.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.theinformation.com/articles/bytedance-tender-valuation",
        "source": "The Information",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-12-09T07:15:00+00:00",
    },
    {
        "id": "grab-gojek-sea-consolidation-2025",
        "title": "Grab and GoTo's on-and-off merger talks resume, with India's own duopoly watching closely",
        "summary": "Reports of revived merger discussions between Southeast Asia's two largest ride-hail and digital-payments groups suggest the region's investors have given up on a competitive equilibrium. For Indian observers, the parallel with Ola and Uber India is unmistakable — and so is the regulatory question of whether such a tie-up could ever clear CCI-equivalent scrutiny in Jakarta and Singapore.",
        "category": "tech",
        "category_label": "Tech",
        "image": "https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/grab-goto-merger-talks",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-02-04T09:00:00+00:00",
    },
    {
        "id": "tabby-tamara-mena-bnpl-2024",
        "title": "Gulf BNPL leaders Tabby and Tamara cross unicorn marks as Indian fintechs eye the GCC",
        "summary": "Back-to-back funding rounds vaulted both Tabby and Tamara into unicorn territory, anchored by PIF and other regional sovereigns. The two now command much of the Gulf's BNPL flow, a market Indian fintechs from Razorpay to Pine Labs have been quietly mapping. The takeaway for Indian founders looking outward is that the GCC's consumer-credit infrastructure gap is still wide, but increasingly well-funded.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/3943746/pexels-photo-3943746.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.reuters.com/business/finance/tabby-tamara-funding-mena",
        "source": "Reuters",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-10-21T11:30:00+00:00",
    },
    {
        "id": "huggingface-enterprise-pivot-2025",
        "title": "Hugging Face's enterprise turn finds eager early customers among Indian IT majors",
        "summary": "The open-source AI platform's enterprise tier, pitched as a private-deployment alternative to closed frontier labs, has reportedly signed several Indian systems-integrators and a large telecom. For TCS, Infosys and Wipro, the appeal is being able to fine-tune and host models inside client environments without licensing handcuffs. The economics of open-weights inference, however, remain stubbornly tied to GPU prices.",
        "category": "tech",
        "category_label": "Tech",
        "image": "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2025/huggingface-enterprise",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-05-14T08:00:00+00:00",
    },
    {
        "id": "cerebras-ipo-filing-2024",
        "title": "Cerebras files for a US listing, and India's AI-compute crowd gets a new comparable",
        "summary": "The wafer-scale AI chip startup's S-1 disclosed heavy revenue concentration with a single Gulf customer, immediately raising both eyebrows and addressable-market questions. For Indian players building inference infrastructure — from Yotta to Tata's GPU cloud — the filing is a useful read on how public investors weigh customer concentration against the breakneck pace of model training demand.",
        "category": "ipo",
        "category_label": "IPO",
        "image": "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=cerebras",
        "source": "SEC",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2024-09-30T14:00:00+00:00",
    },
    {
        "id": "temasek-india-allocation-2025",
        "title": "Temasek lifts its India allocation again, and the cheque sizes are getting harder to ignore",
        "summary": "Singapore's state investor disclosed a meaningful step-up in its India exposure in its annual review, pushing the country into its top-three single-market weightings for the first time. The deployment has tilted toward late-stage consumer internet and financial services, with secondary purchases in Lenskart, Haldiram and a clutch of NBFCs. Domestic founders increasingly treat Temasek as a quasi-anchor for pre-IPO rounds.",
        "category": "vc",
        "category_label": "VC",
        "image": "https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.temasekreview.com.sg/portfolio/india",
        "source": "Temasek Review",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-07-09T06:30:00+00:00",
    },
    {
        "id": "pif-india-platform-2025",
        "title": "Saudi Arabia's PIF readies a dedicated India platform as cross-border capital corridor widens",
        "summary": "Officials linked to the Public Investment Fund have signalled the formation of an India-focused investment platform, designed to anchor large, illiquid bets in infrastructure, EVs and digital public utilities. The vehicle would sit alongside PIF's existing direct stakes and could reshape how Indian late-stage rounds are syndicated. The wager is that India's structural growth narrative now justifies a permanent capital base rather than opportunistic cheques.",
        "category": "vc",
        "category_label": "VC",
        "image": "https://images.pexels.com/photos/5849577/pexels-photo-5849577.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.bloomberg.com/news/pif-india-platform",
        "source": "Bloomberg",
        "is_pinned": False,
        "priority": 8,
        "published_at": "2025-06-11T10:15:00+00:00",
    },
    {
        "id": "reliance-disney-star-merger-2024",
        "title": "Reliance-Disney Star merger closes, redrawing India's streaming map for global advertisers",
        "summary": "The completion of the Reliance-Disney joint venture creates a media entity with combined revenues that dwarf every other Indian streamer. Hotstar and JioCinema users are being migrated into a single product surface, and pricing for both subscriptions and ad inventory is being reset. For global studios and brands, India is now effectively a duopoly market with the new JV and YouTube on one side, and Amazon and Netflix on the other.",
        "category": "tech",
        "category_label": "Tech",
        "image": "https://images.pexels.com/photos/4009401/pexels-photo-4009401.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.reuters.com/business/media-telecom/reliance-disney-merger-close",
        "source": "Reuters",
        "is_pinned": True,
        "priority": 9,
        "published_at": "2024-11-15T05:30:00+00:00",
    },
    {
        "id": "arm-listing-india-design-2024",
        "title": "A year after ARM's blockbuster listing, India's chip-design centres reap the halo",
        "summary": "ARM's first post-IPO year saw it nearly triple in market cap, driven by AI-server licensing optimism. Less visible has been the expansion of its India design footprint, with the company adding hundreds of engineers across Bengaluru and Noida. For Indian semiconductor policy planners, ARM's trajectory has become a working argument that design IP, not fabs, may be the country's most realistic near-term opportunity.",
        "category": "tech",
        "category_label": "Tech",
        "image": "https://images.pexels.com/photos/9028923/pexels-photo-9028923.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.ft.com/content/arm-listing-anniversary",
        "source": "Financial Times",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2024-09-14T09:45:00+00:00",
    },
    {
        "id": "byd-india-entry-talks-2025",
        "title": "BYD's renewed India entry talks stall again on FDI scrutiny, and Tata Motors quietly benefits",
        "summary": "A fresh proposal from Chinese EV major BYD to set up a passenger-car assembly line in India has been parked by an inter-ministerial panel, citing Press Note 3 considerations on neighbouring-country FDI. The delay extends Tata Motors' window of dominance in the sub-twenty-lakh EV segment, just as MG and Hyundai prepare new launches. For BYD, the India market remains the largest growth opportunity it cannot yet access at scale.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/9800027/pexels-photo-9800027.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://www.livemint.com/auto-news/byd-india-fdi",
        "source": "Mint",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-08-21T07:30:00+00:00",
    },
    {
        "id": "temu-india-d2c-pressure-2025",
        "title": "Temu's grey-market India creep pressures domestic D2C margins ahead of festive season",
        "summary": "Even without an official India launch, Temu and its sister platform Shein have been quietly fulfilling Indian orders via cross-border parcel routes, undercutting domestic D2C brands in fashion, home and small electronics. Mensa Brands, GlobalBees and other roll-ups have flagged the price pressure to investors. CBIC's parcel-tax response is still pending, leaving Indian sellers to compete on logistics speed rather than price.",
        "category": "policy",
        "category_label": "Policy",
        "image": "https://images.pexels.com/photos/4498152/pexels-photo-4498152.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://entrackr.com/2025/temu-india-cross-border",
        "source": "Entrackr",
        "is_pinned": False,
        "priority": 6,
        "published_at": "2025-09-04T11:00:00+00:00",
    },
    {
        "id": "elevenlabs-series-c-2025",
        "title": "ElevenLabs hits a multi-billion valuation, and Indian dubbing studios face an existential question",
        "summary": "The voice-AI startup's latest round, anchored by Andreessen Horowitz and ICONIQ, valued the company in the low double-digit billions of dollars. Its multilingual cloning tools already cover most major Indian languages at near-broadcast quality, putting it on a direct collision course with the dubbing studios that have long served Bollywood, OTT platforms and the regional film industries. For Indian voice artists, the contract conversation is shifting from rate cards to licensing.",
        "category": "funding",
        "category_label": "Funding",
        "image": "https://images.pexels.com/photos/164938/pexels-photo-164938.jpeg?auto=compress&cs=tinysrgb&w=800",
        "link": "https://techcrunch.com/2025/elevenlabs-series-c",
        "source": "TechCrunch",
        "is_pinned": False,
        "priority": 7,
        "published_at": "2025-01-23T08:45:00+00:00",
    },
]
