[program:redis]
command=/usr/bin/redis-server --save "" --appendonly no --maxmemory 64mb --maxmemory-policy allkeys-lru --bind 127.0.0.1
autostart=true
autorestart=true
priority=1
stdout_logfile=/var/log/supervisor/redis.out.log
stderr_logfile=/var/log/supervisor/redis.err.log
